set -g mouse on
set -g mode-keys vi
set -g status-keys vi
set -g prefix C-a
unbind C-b
bind C-a send-prefix
bind r source ~/.tmux.conf

# Make window indexes start at 1
set -g base-index 1

# Prevent mouse drag from exiting copy mode
bind -Tcopy-mode MouseDragEnd1Pane send -X copy-selection

# Styling
set -g status-style fg=blue
set -g pane-active-border-style fg=blue

## Status bar info
set -g status-right " #{session_name} "
set -g status-left ""

## Window status
set -g window-status-format " #[fg=gray]#I#[default] #{?window_zoomed_flag,[,}#W#{?window_zoomed_flag,],} "
set -g window-status-current-format "#[reverse] #[default]#[fg=brightyellow,bg=blue]#I#[default]#[reverse] #{?window_zoomed_flag,[,}#W#{?window_zoomed_flag,],} "
