set -g mouse on
set -g mode-keys vi
set -g status-keys vi
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Make window indexes start at 1
set -g base-index 1

# Prevent mouse drag from exiting copy mode
bind -Tcopy-mode MouseDragEnd1Pane send -X copy-selection

# Styling
set -g status-style bg=blue,fg=black
set -g pane-active-border-style fg=blue

